"""empty message

Revision ID: 57aeae796f83
Revises: d204f5f32f56
Create Date: 2025-08-05 16:34:54.483368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57aeae796f83'
down_revision: Union[str, Sequence[str], None] = 'd204f5f32f56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacancies_technologies',
    sa.Column('vacancy_id', sa.Integer(), nullable=False),
    sa.Column('technology_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['technology_id'], ['technologies.technology_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.vacancy_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vacancy_id', 'technology_id')
    )
    op.drop_table('vacancies_main_technologies')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacancies_main_technologies',
    sa.Column('vacancy_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('technology_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['technology_id'], ['technologies.technology_id'], name=op.f('vacancies_main_technologies_technology_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.vacancy_id'], name=op.f('vacancies_main_technologies_vacancy_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vacancy_id', 'technology_id', name=op.f('vacancies_main_technologies_pkey'))
    )
    op.drop_table('vacancies_technologies')
    # ### end Alembic commands ###
