"""empty message

Revision ID: d204f5f32f56
Revises: 
Create Date: 2025-08-05 16:34:23.935767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd204f5f32f56'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('technologies',
    sa.Column('technology_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('technology_id')
    )
    op.create_table('vacancies_experience_specialities',
    sa.Column('vacancy_id', sa.Integer(), nullable=False),
    sa.Column('speciality_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['speciality_id'], ['specialities.speciality_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.vacancy_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vacancy_id', 'speciality_id')
    )
    op.create_table('vacancies_main_technologies',
    sa.Column('vacancy_id', sa.Integer(), nullable=False),
    sa.Column('technology_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['technology_id'], ['technologies.technology_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.vacancy_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vacancy_id', 'technology_id')
    )
    op.drop_table('techologies')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('techologies',
    sa.Column('technology_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('technology_id', name=op.f('techologies_pkey'))
    )
    op.drop_table('vacancies_main_technologies')
    op.drop_table('vacancies_experience_specialities')
    op.drop_table('technologies')
    # ### end Alembic commands ###
